// <auto-generated />
using System;
using Library.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Library.Infastructure.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    [Migration("20250610122224_Inital Migration")]
    partial class InitalMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Library.Domain.Models.AuthorBook", b =>
                {
                    b.Property<int>("IdAuthorBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuthorBook"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdAuthor")
                        .HasColumnType("integer");

                    b.Property<int>("IdBook")
                        .HasColumnType("integer");

                    b.HasKey("IdAuthorBook");

                    b.HasIndex("IdAuthor");

                    b.HasIndex("IdBook");

                    b.ToTable("AuthorBooks");
                });

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.Property<int>("IdBook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBook"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdBook");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Library.Domain.Models.BookGenre", b =>
                {
                    b.Property<int>("IdBookGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBookGenre"));

                    b.Property<int>("IdBook")
                        .HasColumnType("integer");

                    b.Property<int>("IdGenre")
                        .HasColumnType("integer");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("IdBookGenre");

                    b.HasIndex("IdBook");

                    b.HasIndex("IdGenre");

                    b.ToTable("BookGenres");
                });

            modelBuilder.Entity("Library.Domain.Models.BookLending", b =>
                {
                    b.Property<int>("IdBookLending")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBookLending"));

                    b.Property<DateOnly>("DateIssue")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateReturn")
                        .HasColumnType("date");

                    b.Property<int>("IdInstance")
                        .HasColumnType("integer");

                    b.Property<int>("IdReader")
                        .HasColumnType("integer");

                    b.Property<int>("ReturnPeriod")
                        .HasColumnType("integer");

                    b.HasKey("IdBookLending");

                    b.HasIndex("IdInstance");

                    b.HasIndex("IdReader");

                    b.ToTable("BookLendings");
                });

            modelBuilder.Entity("Library.Domain.Models.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmployee"));

                    b.Property<DateOnly>("DateBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdLibrary")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdLibrary");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Library.Domain.Models.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGenre"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdGenre");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("Library.Domain.Models.Instance", b =>
                {
                    b.Property<int>("IdInstance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdInstance"));

                    b.Property<string>("BookNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IdBook")
                        .HasColumnType("integer");

                    b.Property<int>("IdLibrary")
                        .HasColumnType("integer");

                    b.HasKey("IdInstance");

                    b.HasIndex("IdBook");

                    b.HasIndex("IdLibrary");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("Library.Domain.Models.Library", b =>
                {
                    b.Property<int>("IdLibrary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdLibrary"));

                    b.Property<int>("House")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdLibrary");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Library.Domain.Models.Reader", b =>
                {
                    b.Property<int>("IdReader")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReader"));

                    b.Property<DateOnly>("DateBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdReader");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Library.Domain.Новая_папка.Author", b =>
                {
                    b.Property<int>("IdAuthor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAuthor"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdAuthor");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Library.Domain.Models.AuthorBook", b =>
                {
                    b.HasOne("Library.Domain.Новая_папка.Author", "Author")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("IdAuthor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Book", "Book")
                        .WithMany("AuthorBooks")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("Library.Domain.Models.BookGenre", b =>
                {
                    b.HasOne("Library.Domain.Models.Book", "Book")
                        .WithMany("BookGenres")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Genre", "Genre")
                        .WithMany("BookGenres")
                        .HasForeignKey("IdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Library.Domain.Models.BookLending", b =>
                {
                    b.HasOne("Library.Domain.Models.Instance", "Instance")
                        .WithMany("BookLendings")
                        .HasForeignKey("IdInstance")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Reader", "Reader")
                        .WithMany("BookLendings")
                        .HasForeignKey("IdReader")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instance");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("Library.Domain.Models.Employee", b =>
                {
                    b.HasOne("Library.Domain.Models.Library", "Library")
                        .WithMany("Employees")
                        .HasForeignKey("IdLibrary")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Library.Domain.Models.Instance", b =>
                {
                    b.HasOne("Library.Domain.Models.Book", "Book")
                        .WithMany("Instances")
                        .HasForeignKey("IdBook")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Library.Domain.Models.Library", "Library")
                        .WithMany("Instances")
                        .HasForeignKey("IdLibrary")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Library.Domain.Models.Book", b =>
                {
                    b.Navigation("AuthorBooks");

                    b.Navigation("BookGenres");

                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Library.Domain.Models.Genre", b =>
                {
                    b.Navigation("BookGenres");
                });

            modelBuilder.Entity("Library.Domain.Models.Instance", b =>
                {
                    b.Navigation("BookLendings");
                });

            modelBuilder.Entity("Library.Domain.Models.Library", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Instances");
                });

            modelBuilder.Entity("Library.Domain.Models.Reader", b =>
                {
                    b.Navigation("BookLendings");
                });

            modelBuilder.Entity("Library.Domain.Новая_папка.Author", b =>
                {
                    b.Navigation("AuthorBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
